name: flutter_local_notifications_web
description: Web implementation of the flutter_local_notifications plugin
version: 1.0.0
homepage:

dependencies:
  flutter:
    sdk: flutter
  flutter_local_notifications_platform_interface: ^7.0.0
  web: ^0.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

environment:
  sdk: '>=3.3.3 <4.0.0'
  flutter: ">=1.17.0"